version: '2'
services:

  conditorapi:
    container_name: conditor-api
    image: conditor/api:1.0.0-beta.14
    environment :
      LOG_PATH: /var/log
      CONDITOR_API_HOST: 0.0.0.0
      CONDITOR_API_PORT: 63332
      CONDITOR_ES_HOSTS: ${CONDITOR_ES_HOSTS}
      REVERSE_PROXY: ${REVERSE_PROXY}
      JWT_KEY: ${JWT_KEY}
      NODE_ENV: ${NODE_ENV}
      CONDITOR_ES_VERSION: 6.x

    ports:
      - 63332:63332
    networks:
      - apinet
    volumes:
      - ${LOG_PATH}:/var/log
      - ./bin:/app/bin
      - ./.jwt:/app/.jwt
    restart: "on-failure:5"

  conditorpg:
    container_name: conditor-postgres
    image: postgres:11.1
    environment:
      POSTGRES_HOST: ${PG_HOST}
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: conditor
    ports:
      - 5432:5432
    networks:
      - apinet
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  conditorpga:
    container_name: conditor-pgadmin
    image: dpage/pgadmin4:4
    environment: 
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports: 
      - 54322:80
    networks:
      - apinet

networks:
  apinet:
    driver: bridge
